spring.application.name=expensemanager

spring.datasource.url=jdbc:postgresql://dpg-d8l517m47okc73beoqi0-a.singapore-postgres.render.com:5432/expense_tracker_db_obxr?sslmode=require
spring.datasource.username=expense_tracker_db_obxr_user

spring.datasource.password=feiTsDX5bEyPOPOx2jXD4ioQPidStqn7

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect